/**
* @file    dds4ccm_connector.idl
* @author  Marijke Hengstmengel
*
* @brief   idl file for dds4ccm
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef DDS4CCM_CONNECTOR_IDL_
#define DDS4CCM_CONNECTOR_IDL_

#include <Components.idl>
#include "connectors/dds4ccm/idl/dds4ccm_base.idl"
#include "connectors/dds4ccm/idl/dds4ccm_connector_status_listener.idl"

module CCM_DDS
{

   connector DDS_Base {
     uses ConnectorStatusListener error_listener;
     attribute DDS::DomainId_t domain_id
       setraises (NonChangeable);
     attribute string qos_profile
       setraises (NonChangeable);
   };
   connector DDS_TopicBase : DDS_Base {
     attribute string topic_name
       setraises (NonChangeable);
     /// The type_name that will be used by DDS4CCM when
     /// registering the topic to DDS. If empty the default
     /// typename from the DDS typesupport will be used, this
     /// default typename is vendor specific
     attribute string type_name;
   };
};

#endif /* DDS4CCM_CONNECTOR_IDL_ */
