/**
 * @file    dds4ccm_base.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DDS4CCM_BASE_IDL_
#define DDS4CCM_BASE_IDL_

#include "connectors/dds4ccm/idl/dds_rtf2_dcps.idl"
#include "connectors/dds4ccm/idl/dds4ccm_query_filter.idl"
#include "connectors/dds4ccm/idl/dds4ccm_types.idl"

module CCM_DDS
{
  exception AlreadyCreated {
    DataNumberSeq indexes; // of the erroneous
  };

  exception NonExistent{
    DataNumberSeq indexes; // of the erroneous
  };

  exception InternalError{
    DDS::ReturnCode_t error_code;
    DataNumber_t index; // of the erroneous
  };

  exception NonChangeable {
  };

  local interface ContentFilterSetting {
    void set_filter_parameters (in DDS::StringSeq parameters)
      raises (InternalError);
  };
};

#endif /* DDS4CCM_BASE_IDL_ */
