/**
 * @file    usesmulti.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   base of uses multiple ami4ccm test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef USESMULTI_IDL
#define USESMULTI_IDL


#pragma ami4ccm interface "UsesMulti::One"

module UsesMulti
{
  exception InternalError
    {
      long id;
      string error_string;
    };

  // Sender/Receiver interface
  interface One
    {
      long foo (in string in_str, in long cmd, out string answer)
       raises (InternalError);
    };
};

#endif

