/**
 * @file    hello.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   CIAOX11 connector test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_IDL
#define HELLO_IDL


module Hello
{

  struct test_struct {
    long test_long_struct;
  };

  typedef sequence<test_struct> long_seq;

  interface MyFoo
  {
    long hello (in long answer);
    attribute short interface_attrib;
  };

  local interface MyBar
  {
    void bye (in long answer);
    attribute short bar_attrib;
  };

  porttype Write
  {
    uses MyFoo foo_uses;
  };

  porttype Listen
  {
    provides MyFoo foo_prov;
    provides MyBar bar_prov;
    attribute short port_attrib;
    attribute long_seq port_seq_attrib;
  };
};

#endif

