/**
 * @file    example_ga1_msg.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef CX_PORTS__MESSAGES__EXAMPLE_GA1_MSG_IDL
#define CX_PORTS__MESSAGES__EXAMPLE_GA1_MSG_IDL

#include "example_na_defn.idl"
#include "example_ga_defn.idl"

/// @namespace Example
module Example {

    /// @struct GA1_msg
    ///
    @nested(FALSE)
    struct GA1_msg {

        Example::NA4 hdr;

        Example::GA7 data;
    };
};

#endif // CX_PORTS__MESSAGES__EXAMPLE_GA1_MSG_IDL

/// @}
