/**
 * @file    example_ma2_msg.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef CX_PORTS__MESSAGES__EXAMPLE_MA2_MSG_IDL
#define CX_PORTS__MESSAGES__EXAMPLE_MA2_MSG_IDL

#include "example_na_defn.idl"
#include "example_ma_defn.idl"

module A {
  module B {
    const long CONST_VALUE = 5;
  };
};

module A {
  module B {
    typedef long my_typedef;
    module C {
      struct MA2_msgfoo {
        my_typedef bar;
      };
    };
  };
};

module A {
  module B {
    const long SECOND_CONST_VALUE = 5;
  };
};

/// @namespace Example
module Example {

    /// @struct MA2_msg
    ///
    struct MA2_msg {
        Example::NA4 hdr;
        Example::MA4 data;
        boolean trigger;
    }; //@nested(FALSE)
};

#endif // CX_PORTS__MESSAGES__EXAMPLE_MA2_MSG_IDL

/// @}
