/**
 * @file    example_ea2_msg.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef CX_PORTS__MESSAGES__EXAMPLE_EA2_MSG_IDL
#define CX_PORTS__MESSAGES__EXAMPLE_EA2_MSG_IDL

#include "example_na_defn.idl"
#include "example_ea_defn.idl"

/// @namespace Example
module Example {

    /// @struct EA2_msg
    ///
    struct EA2_msg {

        Example::NA4 hdr;

        Example::EA7 data;
    }; //@TopLevel()
};

#endif // CX_PORTS__MESSAGES__EXAMPLE_EA2_MSG_IDL

/// @}
