/**
 * @file    example_ia1_msg.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef CX_PORTS__MESSAGES__EXAMPLE_IA1_MSG_IDL
#define CX_PORTS__MESSAGES__EXAMPLE_IA1_MSG_IDL

#include "example_na_defn.idl"
#include "example_ia_defn.idl"

/// @namespace Example
module Example {

    /// @struct IA1_msg
    ///
    struct IA1_msg {

        Example::NA4 hdr;

        Example::IA4 data;
    }; //@TopLevel()
};

#endif // CX_PORTS__MESSAGES__EXAMPLE_IA1_MSG_IDL

/// @}
