/**
 * @file    example_ga2_msg.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef CX_PORTS__MESSAGES__EXAMPLE_GA2_MSG_IDL
#define CX_PORTS__MESSAGES__EXAMPLE_GA2_MSG_IDL

#include "example_na_defn.idl"
#include "example_ga_defn.idl"

/// @namespace Example
module Example {

    /// @struct GA2_msg
    ///
    struct GA2_msg {

        Example::NA4 hdr;

        Example::GA8 data;
    }; //@TopLevel()
};

#endif // CX_PORTS__MESSAGES__EXAMPLE_GA2_MSG_IDL

/// @}
