/**
 * @file    idl_conversion_sender.idl
 * @author  Marcel Smit
 *
 * @brief   Sender component declaration for the IDL stress test.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef IDL_CONVERSION_SENDER_IDL_
#define IDL_CONVERSION_SENDER_IDL_

#include "idl_conversionSE.idl"
#include <ccm_timed_trigger.idl>

module IDL_Conversion_Test
{
  component Sender
  {
    port Example::IDLConversionTestConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;
    uses CCM_TT::TT_Scheduler tt_scheduler;

    attribute unsigned short rate;
    attribute unsigned short iterations;

    /// Test that the following DDS4CCM defined types can be used as
    /// attribute, which required they have AnyTypeCode support
    /// enabled
    attribute CCM_DDS::DataNumber_t data_number;
    attribute CCM_DDS::DataNumberSeq data_number_seq;
    attribute CCM_DDS::ListenerMode listener_mode;
    attribute CCM_DDS::AccessStatus accesss_status;
    attribute CCM_DDS::InstanceStatus instance_status;
    attribute CCM_DDS::ReadInfo read_info;
    attribute CCM_DDS::ReadInfoSeq read_info_seq;
  };
};

#endif /* IDL_CONVERSION_SENDER_IDL_ */
