/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  enum Option
  {
    ONE,
    TWO,
    THREE
  };

  union Topic switch(Option)
  {
    case ONE: string text;
    case TWO: unsigned long number;
    case THREE: boolean flag;
  }; //@nested(FALSE)
};

#endif
