include::_{backend}_settings.adoc[]

= Manually compile *AXCIOMA* applications

This document describes how to compile *AXCIOMA* applications without
using MPC or BRIX11.

The examples in this document follow the
<<philosophy.adoc#,*AXCIOMA* philosophy>> and the directory structure
mentioned in the <<good_practice.adoc#,Good practice>> guide.

== IDL

*AXCIOMA* basically divides the IDL in four different categories:

.  The "data" IDL +
This defines the data types and interfaces used throughout the
application.

.  The "pattern" IDL +
This is the implied IDL (generated from the data IDL or created
manually), that provides the interfaces for a specific interaction
pattern
** <<{xref_docs_root}/corba4ccm/corba4ccm.adoc#,synchronous request/reply>>
** <<{xref_docs_root}/ami4ccm/ami4ccm.adoc#,asynchronous request/reply>>
** <<{xref_docs_root}/dds4ccm/dds4ccm.adoc#,state/event>>
include::{ciaox11_src_root}/connectors/psdd4ccm/docs/src/compilation.asc[tag=pattern1,opts=optional]

.  The "connector" IDL +
Defines the connector that realizes a specific interaction pattern.
This can be generated out of the data IDL or manually created.

.  The "business component" IDL +
The user defined component.

This page will give an overview of what IDL and what sources are
generated by the RIDL compiler and how to compile these.

This page only provides a description of the synchronous request/reply pattern.
The description of the full list of RIDL command line options as well as libraries and MPC projects for
*AXCIOMA* component development can be found <<ridlc.adoc#,here>>
and <<lib_mpc.adoc#,here>>.

=== Data IDL

It all starts with the interface definition in IDL:

[source,idl]
.foo_base.idl
----------------------------------------------------
module Hello
{
  exception Ball
  {
    string error;
  };

  interface MyFoo
  {
    string foo (in string in_str, out string answer)
      raises (Ball);

    attribute short foo_attrib;

    attribute short foo_excep
      getraises (Ball)
      setraises (Ball);
  };
};

----------------------------------------------------

Every part of an *AXCIOMA* application needs the stub library of the
data types and interfaces:

Command::
 `$X11_BASE_ROOT/bin/ridlc`

Command line options::
-----------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -Sci
        -Ssi
        -Sa
        -St
        -Sp
        -SS
        -Ssh
        -Gxhst
        -Wb,base_export_macro=FOO
        -Wb,base_export_include=foo
        foo_base.idl
-----------------------------------

The result of the above mentioned command line is as follows:

[cols="<,<",options="header",]
|==============================================================
|File name |Kind
|<idl_file>C[P].cpp/h |Stub files
|<idl_file>_stub_export.h |Export defines for the stub library.
|==============================================================

=== Pattern IDL

This is the implied IDL that should be used for a certain pattern

* <<{xref_docs_root}/corba4ccm/corba4ccm.adoc#,synchronous request/reply>>
* <<{xref_docs_root}/ami4ccm/ami4ccm.adoc#,asynchronous request/reply>>
* <<{xref_docs_root}/dds4ccm/dds4ccm.adoc#,state/event>>
include::{ciaox11_src_root}/connectors/psdd4ccm/docs/src/compilation.asc[tag=pattern2,opts=optional]


==== Synchronous request/reply

For the synchronous request/reply pattern it only involves the Local
Executor Mapping IDL (lem).

Command::
`$X11_BASE_ROOT/bin/ridlc`

Command line options::

-----------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -Sci
        -Ssi
        -Sa
        -St
        -Sp
        -SS
        -Ssh
        -Glem,gen
        -Sch
        -Scc
        -Scp
        -Wb,base_export_macro=FOO
        -Wb,base_export_include=foo
        foo_base.idl
-----------------------------------

Now the following files are generated:

[cols="<,<",options="header",]
|======================================================================
|File name |Kind
|<idl_file>E.idl |LEM IDL file
|<idl_file>EC.cpp/h |LEM Stub files
|<idl_file>_lem_stub_export.h |Export defines for the lem stub library.
|======================================================================

=== Connector IDL

This make sure that the patterns, defined in the pattern IDL will be
compiled into a certain implementation of that pattern. When an
application uses the synchronous reply/pattern, an implementation for
that pattern might be CORBA. This IDL makes sure that the IDL which
realizes the CORBA implementation is generated.

Command::
`$X11_BASE_ROOT/bin/ridlc`

Command line options::

-----------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -I$CIAOX11_ROOT
        -Sci
        -Ssi
        -Sa
        -St
        -Gcorba4ccm,conn
        -Gxhsk
        -Sch
        -Scc
        -Scp
        -Wb,base_export_macro=FOO
        -Wb,base_export_include=foo
        foo_base.idl
-----------------------------------

The parameter `-Gcorba4ccm,conn` makes sure that all needed implied IDL
and C++ source code is generated for an implementation of a CORBA
connector as follows:

[cols="<,<",options="header",]
|=======================================================================
|File name |Kind
|<idl_file>_cc.idl |Implied IDL for the CORBA4CCM connector.

|<idl_file>_ccC.cpp/h |Stub files for the CORBA4CCM connector

|<idl_file>_ccCP.h |Proxy file for the CORBA4CCM connector stub

|<idl_file>_cc_stub_export.h |Export defines for the CORBA4CCM connector
stub.

|<idl_file>_cc_exec.cpp/h |Implementation of the CORBA4CCM connector itself.

|<idl_file>_cc_exec_export.h |Export defines for the CORBA4CCM connector
implementation.

|<idl_file>_cc_svnt.cpp/h |Servant implementation for the CORBA
connector.

|<idl_file>_cc_svnt_export.h |Export defines for the servant of the
CORBA4CCM connector.

|<idl_file>_ccE.idl |LEM Stub IDL for the CORBA4CCM connector

|<idl_file>_ccEC.cpp/h |LEM stub files.

|<idl_file>_cc_lem_stub_export.h |Export defines for the LEM stub.

|<idl_file>_ccS.h |Skeleton part of the CORBA4CCM connector

|<idl_file>_ccSP.h |Proxy for the CORBA4CCM connector.

|<idl_file>S.cpp/h |CORBA part of the CORBA4CCM connector.

|<idl_file>SP.h |Proxy for the skeleton.

|<idl_file>_skel_export.h |Export defines for the skeleton library.
|=======================================================================

=== Business component IDL

The business components are making use of the data types and/or
interfaces defined in the data IDL. In this example one component uses
the `MyFoo` interface (the Sender component), the other (the Receiver)
component provides this interface:

Sender Component

[source,idl]
.foo_base_sender.idl
--------------------------
module Hello
{
  component Sender
  {
    uses MyFoo run_my_foo;
  };
};

--------------------------

Receiver Component

[source,idl]
.foo_base_receiver.idl
-----------------------------
module Hello
{
  component Receiver
  {
    provides MyFoo do_my_foo;
  };
};

-----------------------------

To create all files needed for a component, the following command
can be used.

Command::
`$X11_BASE_ROOT/bin/ridlc`

Command line options::

------------------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -I$CIAOX11_ROOT
        -I$CIAOX11_ROOT/ccm
        -Sci
        -Ssi
        -Sa
        -St
        -Gcomp
        -SS
        -Ssh
        -Scc
        -Scp
        -Wb,base_export_macro=FOO_SENDER
        -Wb,base_export_include=foo_sender
        foo_base_sender.idl
------------------------------------------

Again, the generated files:

[cols="<,<",options="header",]
|===================================================================
|File name |Kind
|<idl_file>C.h |Stub header
|<idl_file>E.idl |LEM stub IDL file.
|<idl_file>EC.cpp/h |LEM stub files.
|<idl_file>_lem_stub_export.h |Export defines for the LEM stub.
|<idl_file>_svnt.cpp/h |Implementation of the component servant.
|<idl_file>_svnt_export.h |Export defines for the component servant.
|<idl_file>_exec_export.h |Export defines for the component itself.
|===================================================================

=== Additional

==== Paths

When using different directories for the above mentioned IDL files, one
should add more include paths to the command line. Another include path
can be added with `-I`.

==== Business Component Executor starter code

The RIDL compiler is able to generate the so called business component
starter code. When doing this, all boiler plate code will be generated,
including re-generation markers. link:./executor_starter_code.html[This
page] provides more information regarding the Business Component
Executor starter code and the
<<executor_starter_code.adoc#_re_generation_markers,re-generation markers>>.

== GCC command line

Besides the command line parameters mentioned in the TAOX11 paragraph
<<{xref_docs_root}/taox11/compilation.adoc#_gcc_command_line,GCC command
line>>, `-fPIC` should be added while compiling the *AXCIOMA* sources.

There are no additional command line parameters needed in *AXCIOMA* when
linking the sources.

== Examples

=== Compilation

Now that all sources are generated by the RIDL compiler, we can compile
these sources. Again, when compiling in different directories, add more
include paths the command lines.

==== Data code

In this case there's just one library (the stub library) which all other
items in this example need. It should be compiled in the following way:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I. -DFOO_STUB_BUILD_DLL  -c -fPIC -o .shobj/foo_baseC.o foo_baseC.cpp
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Pattern code

Only the LEM stub should be compiled here:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -DFOO_LEM_STUB_BUILD_DLL -c -fPIC -o .shobj/foo_baseEC.o foo_baseEC.cpp
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Connector code

Only the CORBA4CCM connector will be used in this example but that results
in the compilation of several files. All is compiled into on library
since no other component/connector but the CORBA4CCM connector itself uses
the (lem)stub and skeleton libraries.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I../../../.. -I../../../../ccm -DFOO_SKEL_BUILD_DLL -DFOO_CC_STUB_BUILD_DLL -DFOO_CC_LEM_STUB_BUILD_DLL -DFOO_CC_EXEC_BUILD_DLL -DFOO_CC_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_baseS.o foo_baseS.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I../../../.. -I../../../../ccm -DFOO_SKEL_BUILD_DLL -DFOO_CC_STUB_BUILD_DLL -DFOO_CC_LEM_STUB_BUILD_DLL -DFOO_CC_EXEC_BUILD_DLL -DFOO_CC_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_base_ccEC.o foo_base_ccEC.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I../../../.. -I../../../../ccm -DFOO_SKEL_BUILD_DLL -DFOO_CC_STUB_BUILD_DLL -DFOO_CC_LEM_STUB_BUILD_DLL -DFOO_CC_EXEC_BUILD_DLL -DFOO_CC_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_base_ccC.o foo_base_ccC.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I../../../.. -I../../../../ccm -DFOO_SKEL_BUILD_DLL -DFOO_CC_STUB_BUILD_DLL -DFOO_CC_LEM_STUB_BUILD_DLL -DFOO_CC_EXEC_BUILD_DLL -DFOO_CC_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_base_cc_exec.o foo_base_cc_exec.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I../../../.. -I../../../../ccm -DFOO_SKEL_BUILD_DLL -DFOO_CC_STUB_BUILD_DLL -DFOO_CC_LEM_STUB_BUILD_DLL -DFOO_CC_EXEC_BUILD_DLL -DFOO_CC_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_base_cc_svnt.o foo_base_cc_svnt.cpp
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Business component code

At last the component code can be compiled. Business components should
not have any relation to the implementation of the patterns, only to the
pattern sources and libaries themselves!

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I. -I.. -I../base -I../base/generated_code -Igenerated_code -I../../../../.. -I../../../../../ccm -DFOO_SENDER_LEM_STUB_BUILD_DLL -DFOO_SENDER_EXEC_BUILD_DLL -DFOO_SENDER_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_senderEC.o foo_senderEC.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I. -I.. -I../base -I../base/generated_code -Igenerated_code -I../../../../.. -I../../../../../ccm -DFOO_SENDER_LEM_STUB_BUILD_DLL -DFOO_SENDER_EXEC_BUILD_DLL -DFOO_SENDER_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_sender_svnt.o foo_sender_svnt.cpp
g++ -std=c++11 -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -I. -I.. -I../base -I../base/generated_code -Igenerated_code -I../../../../.. -I../../../../../ccm -DFOO_SENDER_LEM_STUB_BUILD_DLL -DFOO_SENDER_EXEC_BUILD_DLL -DFOO_SENDER_SVNT_BUILD_DLL  -c -fPIC -o .shobj/foo_sender_exec.o foo_sender_exec.cpp
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Linking

==== Data code

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -pthread -Wl,-O3 -shared -Wl,-h -Wl,libfoo_stub.so.1.4.1 -o libfoo_stub.so.1.4.1 .shobj/fooC.o -m64 -Wl,-E -L../lib -L.  -L$ACE_ROOT/lib  -L$TAOX11_ROOT/../lib  -L../lib  -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Pattern code

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -pthread -Wl,-O3 -shared -Wl,-h -Wl,libfoo_lem_stub.so.1.4.1 -o libfoo_lem_stub.so.1.4.1 .shobj/fooEC.o -m64 -Wl,-E -L../lib -L.  -L$ACE_ROOT/lib  -L$TAOX11_ROOT/../lib  -L../lib  -lfoo_stub -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Connector code

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -pthread -Wl,-O3 -shared -Wl,-h -Wl,libfoo_corba_conn.so.1.4.1 -o libfoo_corba_conn.so.1.4.1 .shobj/fooS.o .shobj/foo_ccC.o .shobj/foo_ccEC.o .shobj/foo_cc_exec.o .shobj/foo_cc_svnt.o -m64 -Wl,-E -L../lib -L.  -L$ACE_ROOTlib  -L$TAOX11_ROOT/../lib  -L../../../../lib  -L../../../../connectors/corba4ccm/corba4ccm  -L../lib  -lfoo_stub -lfoo_lem_stub -lciaox11_corba4ccm_impl -lciaox11_ccmobject_skel -lciaox11_ccmobject_stub -ltaox11_portable_server -lTAO_PortableServer -lciaox11_logger -lciaox11_ccm_session_stub -lciaox11_ccm_stub -ltaox11_anytypecode -lTAO_AnyTypeCode -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

==== Business component code

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -pthread -Wl,-O3 -shared -Wl,-h -Wl,libfoo_sender_exec.so.1.4.1 -o libfoo_sender_exec.so.1.4.1 .shobj/foo_sender_exec.o .shobj/foo_senderEC.o .shobj/foo_sender_svnt.o -m64 -Wl,-E -L../../lib -L.  -L$ACE_ROOTlib  -L$TAOX11_ROOT/../lib  -L../lib  -L../../../../../lib  -L../../lib  -lfoo_lem_stub -lfoo_stub -lciaox11_logger -lciaox11_ccm_session_stub -lciaox11_ccm_stub -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
