@startuml
'https://plantuml.com/component-diagram

skinparam componentstyle uml2

component "**FooConnectorFragmentA**" as FooConnectorFragmentA #DarkRed;text:white;line:white;
component "**FooConnectorFragmentB**" as FooConnectorFragmentB #DarkRed;text:white;line:white;

[ComponentA] "Foo " 0)- [FooConnectorFragmentA]
[FooConnectorFragmentA] <-> [FooConnectorFragmentB] : "  "
[FooConnectorFragmentB] "Foo" 0)- [ComponentB]

@enduml
