include::_{backend}_settings.adoc[]

= Good practice

== Structure

From reading the page <<philosophy.adoc#,*AXCIOMA* philosophy>> it
becomes clear there are 5 distinct parts/steps to any *AXCIOMA* application,
where _Deployment_ should be treated as a separate item.
Deployment is mentioned here as an example.

1.  Data IDL
2.  Interaction patterns
3.  Interaction pattern implementation in connectors
4.  Business components
5.  Deployment

When following this structure, the following directory structure is used
in several *AXCIOMA* tests and examples.

[source]
-------------------
application
data (base)
patterns
connectors
components
  Component A
  Component B
  Component .. n
descriptors
-------------------

If this structure is not used in the *AXCIOMA* tests/examples, the
structure can be determined from the MPC files.

== MPC base projects

It is good practice to let the <<{xref_docs_root}/taox11/ridlc.adoc#,RIDL
compiler>> generate the {cxx11} source files into a separate
(sub)directory. This way the IDL and MPC files do not get mixed up with
generated code. To make sure that all *AXCIOMA* tests are behaving the
same, the *AXCIOMA* link:{docs_root}/../../ciaox11/MPC/config[MPC/config] directory and its
subdirectories contain several MPC test base projects. These MPC base
projects make sure that the *AXCIOMA* tests have at least the following
generation and compilation settings:

* All generated code will be put in the `generated_code` subdirectory
* All libraries will be placed in a directory called `lib`
in the root of the test. This directory will be included in the link
command.
* The business component executor starter code will be (re)generated
when the MPC feature `ciaox11_noregen_exec` is set to zero (0) in
`default.features` (see <<executor_starter_code.adoc#,this page>>).

== Example

Check out the
link:{docs_root}/../../ciaox11/examples/hello/extended[Hello
example in this directory]:

.ciaox11/examples/hello/extended/
dirlist::../../examples/hello/extended/*[]

This example shows how the various interaction patterns and
components are located in the directory structure listed above.

=== Data

This directory may contain IDL files containing the data types and
interfaces which are needed throughout the application. The output of
these IDL files are stub libraries which in turn are used by the
interaction pattern implementations and user defined business
components. +
The MPC files therefor contains two projects: one to generate the stub
files and one to compile them. The output is one or more stub libraries.

=== Patterns

This directory only contains MPC files since the implied interaction
pattern IDL is generated out of the data IDL. It is good practice to use
one MPC per interaction pattern per data IDL file. See for example this
directory:

.ciaox11/examples/hello/extended/patterns
dirlist::../../examples/hello/extended/patterns/*.mpc[]

This directory contains one MPC file for each pattern interface per data IDL file. +
Each MPC file contains two projects: one to compile the data IDL to
generate the implied interaction pattern IDL and {cxx11} sources and one
to compile them. The output is a stub library per interaction pattern
per data IDL.

=== Connectors

The MPC files in this directory make sure that the implied IDL for the
implementation of the used interaction patterns and the interaction
connectors themselves are generated and compiled. Again, it is good
practice to define one MPC per interaction pattern, per data IDL.

.ciaox11/examples/hello/extended/connectors
dirlist::../../examples/hello/extended/connectors/*.mpc[]

The connectors directory of this example contains separate MPC files for
each connector. Optionally skeleton generation could be separated in another
MPC file when needed for sharing between CORBA4CCM and AMI4CCM
connectors for the same data IDL (providing synchronous and asynchronous
request/reply support for the same data interface). +
Again, each MPC contains two projects: one to generate the implied IDL out of the
data IDL and to generate the {cxx11} sources out of this implied IDL and
one project to compile all generated code into the implementation
library of a certain interaction pattern. +
The output is one library per interaction pattern per data IDL,
containing the implementation of the interaction pattern for that
specific data IDL.

=== Components

In this example each component has its own directory containing one MPC
file, one IDL file, and the implementation of the business code (
`*_exec.{cpp,h}`) where the business code was initially generated by the
RIDL compiler (see <<executor_starter_code.adoc#,this page>> for more
info).

.ciaox11/examples/hello/extended/components
dirlist::../../examples/hello/extended/components/*[recurse=1]

Since user defined components do not have any knowledge about the
implementation of interaction patterns,
components should not have any reference to the `connectors`
directory. +
The output is one library, containing the business logic for the user
defined business component.

=== Descriptors

The descriptors directory contains the deployment plan together with a perl script
which starts and tears down the application, using the *AXCIOMA*
<<{xref_docs_root}/dancex11/d+c-overview.adoc#,Deployment and configuration>>
framework.

.ciaox11/examples/hello/extended/descriptors
dirlist::../../examples/hello/extended/descriptors/*[]

== Compilation

As mentioned in the
<<getting_started.adoc#_developing_with_strong_axcioma_strong,Getting Started>> page,
there are two ways to compile your application:

.  The <<{xref_docs_root}/taox11/getting_started.adoc#_classic_development,classic>> way.
.  with the aid of <<{xref_docs_root}/brix11/brix11.adoc#,BRIX11>>. +
* Go to the root of your application and run `brix11 make .` to create
the make files and compile your application.
* Run your application by invoking `brix11 run test descriptors/`.
+
Be sure that the bin directory is in your path.

== More

More information about the *AXCIOMA* libraries can be found
<<lib_mpc.adoc#,here>>.

Although *not recommended*, one can build an *AXCIOMA* application without
the aid of MPC. More information about this can be found on
<<compilation.adoc#,this page>>.
