include::_{backend}_settings.adoc[opts=optional]

= CIAOX11 Internals

CIAOX11 supports most of the features of CIAO but the internal
architecture is completely different. Where CIAO is heavily based on
CORBA, the CIAOX11 internals are almost fully CORBA agnostic.

== Container

CIAOX11 only supports one type of container, the session container.
This container is created by the CIAOX11 deployment installation handlers
and only supports session components. A session component is a component
which provides the LwCCM session defined lifecycle APIs. The container is
an internal entity of the CIAOX11 framework, it is not accessible for
user components.

== ExecutorLocator

The CIAOX11 ExecutorLocater is a local interface which gives access to
all the component specific entities like context, and
executors. The ExecutorLocator is the interface that is used by the
CIAOX11 container to access the component. The C entry point as part of
the servant DLL returns a reference to a CIAOX11 executor locator. At
the moment a component or connector has attributes which can be set
through the deployment plan a component specific configuration method
(`configure`) is generated by RIDL. This operation accepts a
sequence of `ConfigValue` structs. A
ConfigValue struct consists of a `name` as string and a `value` as any.
When a ConfigValue is given for a specific attribute `configure`
will set the value coming from the deployment plan onto the component
executor. The method will try to set all values. At the moment multiple
values have been incorrectly set in the deployment plan they all will be
reported back as invalid.

== Context

For each component or connector a context is generated. This context
gives access to all receptacles that are used by the component or
connector. With CIAOX11 it also provides access to the service registry
which is part of the CIAOX11 container.

== Valuetype

CIAOX11 doesn't use valuetypes for the Cookie and ConfigValue types. The
ConfigValue type has been changed from valuetype to a struct and the Cookie
type has been changed to a string. This reduces the footprint and dependencies for
CIAOX11.

== Homes

CIAOX11 doesn't support homes.

== Usage of Any and Typecodes with CIAOX11

CIAO as LwCCM implementation has support for Any and Typecodes enabled
by default. For any user written IDL the TAO_IDL compiler will generate
full support for Any and Typecode. This has the advantage that a
user can use Any/Typecode support whenever needed, but it does lead to a
significant footprint increase. CIAOX11 doesn't enable Any and Typecode
support for user IDL by default. Only when you want to use an IDL type
for a component/connector attribute you have to enable the Any and
Typecode support when compiling your IDL file. This can be done by
deriving the MPC project for the specific IDL file from
`taox11_anytypecode` or by specificing `idlflags -= -Sa -St` in the
IDL_Files section for your IDL file. When you only need to link
with the Any/Typecode libraries you can use the
`taox11_core_anytypecode` MPC base project.

== CIAO and CIAOX11 compatibility

A requirement for CIAOX11 was the ability to reuse any generated
IDL and deployment plan that a user has for CIAO. Because of this
compatibility the generated _svnt.\{h,cpp} files use the same naming and
entry point as CIAO.
