/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  @nested(FALSE)
  struct Topic
  {
    string key;
    unsigned long device;
    unsigned long msgid;
    boolean status;
    double value;
  };
};

#endif
