/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
* Chamber of commerce Rotterdam nr.276339, The Netherlands
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  struct Topic
  {
    string key;
    unsigned long device;
    unsigned long msgid;
    boolean status;
    double value;
  }; //@TopLevel()
};

#endif
