/**
 * @file    unkeyed_writer_receiver.idl
 * @author  Marcel Smit
 *
 * @brief   Receiver component declaration for the Unkeyed Writer test.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef UNKEYED_WRITER_RECEIVER_IDL_
#define UNKEYED_WRITER_RECEIVER_IDL_

#include "unkeyed_writerSE.idl"

module UnkeyedWriterTest
{
  component Receiver
  {
    port UnkeyedWriterMessageConnector::DDS_Listen info_out;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif /* UNKEYED_WRITER_RECEIVER_IDL_ */
