/**
 * @file    non_changeable_component.idl
 * @author  Marcel Smit
 *
 * @brief   Component IDL for the non_changeable test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef NON_CHANGEABLE_COMPONENT_IDL_
#define NON_CHANGEABLE_COMPONENT_IDL_

#include "commonSE.idl"

component NonChangeableComponent
{
  port CommonTestConnector::DDS_Get info_get;
};

#endif /* NON_CHANGEABLE_COMPONENT_IDL_ */
