/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
* Chamber of commerce Rotterdam nr.276339, The Netherlands
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  struct Nested
  {
    boolean flag;
    double rate;
    char opt;
  };

  struct Topic
  {
    string category;
    string description;
    unsigned long value;
    Nested data;
  }; //@TopLevel()
};

#endif
