/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  typedef string<10> Topic; //@nested(FALSE)
};

#endif
