/**
 * @file    hello_sender.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "hello.idl"

module Hello
{
  component Sender
  {
    /// For synchronous invocation
    uses MyFoo run_my_foo;
  };
};

#endif
