/**
 * @file    psl_sample_lost_receiver.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef PSL_SAMPLE_LOST_RECEIVER_IDL_
#define PSL_SAMPLE_LOST_RECEIVER_IDL_

#include "commonSE.idl"
#include <ccm_timed_trigger.idl>

module PSL_SampleLostTest
{
  component Receiver
  {
    port CommonTestConnector::DDS_Get    info_get;
    port CommonTestConnector::DDS_Listen info_out;

    provides CCM_DDS::ConnectorStatusListener connector_status;

    uses CCM_TT::TT_Scheduler tt_scheduler;
   };
};

#endif /* PSL_SAMPLE_LOST_RECEIVER_IDL_ */
