include::_{backend}_settings.adoc[]

= DDSX11 Files

== Overview of generated files for DDSX11

The DDSX11 product generates multiple additional files. This document
gives an overview of the generated files and their meaning. As input we
assume `foo.idl` which contains the type definitions. Some of the
generated files could be empty when `foo.idl` only 'simple'
type declarations (and no valuetypes, interfaces etc.).

The following files are generated by RIDL to support the IDL to
{cxx11} type system

.{cxx11} type support
[cols="<1,<3",options="header",]
|=======================================================================
|File |Purpose
|fooC.h |IDL to {cxx11} type support header

|fooC.cpp |IDL to {cxx11} type support implementation

|fooCP.h |IDL to {cxx11} type support proxy and TAO CDR (de)marshaling
support. Contains all code that is needed for TAOX11 to use these types.
At the moment these types are 100% for DDS the TAO CDR (de)marshaling
support can be disabled using the `-Scdr` RIDL commandline options and
the generation of this file can be suppressed using `-Scp`.
|=======================================================================

The following files are generated by RIDL to provide the IDL to {cxx11}
type specific DDS data reader and data writer interfaces. The type
specific DDS data reader and data writer are not generated when a type
is marked with nested TRUE.

.{cxx11} type specific DDS data reader and writer
[cols="<1,<3",options="header",]
|=======================================================================
|File |Purpose
|foo_dds_typesupport.h |Type support header which has to be included in
the user code to get access to the DDS {cxx11} API for a specific {cxx11} type

|foo_dds_typesupport.cpp |Type support implementation. Normally compiled
together the the DDS (vendor) type support into one shared library

|foo_typed_entities.idl |Typed data reader and datawriter IDL interfaces

|foo_typed_entitiesC.h |IDL to C++11 stub header for the DDS typed
interfaces

|foo_typed_entitiesC.cpp |IDL to C++11 stub implementation for the DDS
typed interfaces

|foo_typed_entitiesCP.h |IDL to C++11 stub type support proxy and TAO
CDR (de)marshaling support for the DDS typed interfaces. Contains all
code that is needed for TAO to use these types. At the moment these
types are 100% for DDS the TAO CDR (de)marshaling support can be
disabled using the `-Scdr` RIDL commandline options and the generation
of this file can be suppressed using `-Scp`.
|=======================================================================

To integrate a DDS vendor that does not support IDL to {cxx11} RIDL
generates a new IDL file containing the defined types within the
`DDS_Native` module.

.DDS vendor specific IDL
[cols="<1,<3",options="header",]
|====================================================================
|File |Purpose
|foo_dds.idl |All user defined types but within the DDS_Native module
|====================================================================

The `foo_dds.idl` is used by the DDS vendor specific IDL compiler to
generate the needed support by using the DDS vendor delivered IDL
compiler. The DDS vendor only sees all implied types as defined within
the `DDS_Native` module. The DDS vendor does not see the original user
defined `foo.idl`.

include::{ciaox11_src_root}/ddsx11/vendors/ndds/docs/src/ddsx11_files.asc[]

In order to convert between the IDL to {cxx11} type system and the vendor
specific {cpp} type system a set of conversion traits and a type support
factory are generated. The
conversion traits are vendor specific and are used by DDSX11 to
implement the DDS API using the IDL to {cxx11} language mapping without
knowing any vendor specific details.

.{cxx11} type conversion traits
[cols="<1,<3",options="header",]
|=======================================================================
|File |Purpose
|foo_dds_traits.h |Conversion traits for the conversion between the IDL
to {cxx11} type system and the DDS vendor provided IDL to {cpp} type system.
Not intended to be included by the user code
|=======================================================================

