/**
 * @file    hello_receiver.idl
 * @author  Martin Corino
 *
 * @brief   Receiver component for minimal sync manual example
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_RECEIVER_IDL_
#define HELLO_RECEIVER_IDL_

#include <Components.idl>

#include "hello.idl"
#include "port_r.idl"

module Hello
{

  struct rec_struct {
    long rec_long;
  };

  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
    attribute rec_struct  rec_struct_attrib;

    mirrorport portFooPortR foo_port_r;
  };
};

#endif /* HELLO_RECEIVER_IDL_ */
