/**
 * @file    psdd4ccm_testlog.h
 * @author  Martin Corino
 *
 * @brief   CORBA C++11 Test Logging module
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef PSDD4CCM_TESTLOG_H
#define PSDD4CCM_TESTLOG_H

#include "psdd4ccm/logger/psdd4ccm_log.h"

#if defined(X11_NLOGGING)

#define PSDD4CCM_TEST_LOGGER   x11_logger::NULL_LogType

#else

#define PSDD4CCM_TEST_LOGGER \
  CIAOX11::PSDD4CCM::psdd4ccm_logger::PSDD4CCM_Test_Log_Module::log_type

#endif /* !X11_NLOGGING */

#define PSDD4CCM_TEST_TRACE      X11_TRACE_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_DEBUG      X11_DEBUG_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_INFO       X11_INFO_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_WARNING    X11_WARNING_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_ERROR      X11_ERROR_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_CRITICAL   X11_CRITICAL_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_PANIC      X11_PANIC_LOG(PSDD4CCM_TEST_LOGGER)


#define PSDD4CCM_TEST_TRACE_W    X11_TRACE_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_DEBUG_W    X11_DEBUG_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_INFO_W     X11_INFO_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_WARNING_W  X11_WARNING_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_ERROR_W    X11_ERROR_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_CRITICAL_W X11_CRITICAL_W_LOG(PSDD4CCM_TEST_LOGGER)
#define PSDD4CCM_TEST_PANIC_W    X11_PANIC_W_LOG(PSDD4CCM_TEST_LOGGER)

#endif /* PSDD4CCM_TESTLOG_H */
