/**
 * @file    ndds_dcps_types.idl
 * @author  Marcel Smit
 *
 * @brief   Placeholder for anytypecode.
 *          RTI NDDS compliant IDL code.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef NDDS_DCPS_TYPES_IDL_
#define NDDS_DCPS_TYPES_IDL_

#define HANDLE_TYPE_NATIVE      long

module DDS {
  typedef long DomainId_t;

  // @todo, move this to its own file so that we can put the converter into the core????
  typedef unsigned long long_4[4];

  typedef sequence<string> StringSeq;
};

#endif /* NDDS_DCPS_TYPES_IDL_ */
