// -*- C++ -*-
/**
 * @file    ciaox11_deployment_handler_export.h
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef CIAOX11_DEPLOYMENT_HANDLER_EXPORT_H
#define CIAOX11_DEPLOYMENT_HANDLER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL)
#  define CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL */

#if !defined (CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL)
#  define CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL 1
#endif /* ! CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL */

#if defined (CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL) && (CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL == 1)
#  if defined (CIAOX11_DEPLOYMENT_HANDLER_BUILD_DLL)
#    define CIAOX11_Deployment_Handler_Export ACE_Proper_Export_Flag
#    define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CIAOX11_DEPLOYMENT_HANDLER_BUILD_DLL */
#    define CIAOX11_Deployment_Handler_Export ACE_Proper_Import_Flag
#    define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CIAOX11_DEPLOYMENT_HANDLER_BUILD_DLL */
#else /* CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL == 1 */
#  define CIAOX11_Deployment_Handler_Export
#  define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARATION(T)
#  define CIAOX11_DEPLOYMENT_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CIAOX11_DEPLOYMENT_HANDLER_HAS_DLL == 1 */

#endif /* CIAOX11_DEPLOYMENT_HANDLER_EXPORT_H */

// End of auto generated file.
