/**
 * @file    hello_sender_comp.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   idl for sender component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "hello.idl"

#pragma ami4ccm receptacle "Hello::Sender_comp::run_my_foo"

module Hello
{
  component Sender_comp
  {
    /// For synchronous invocation
    uses MyFoo_obj run_my_foo;
  };
};

#endif
