/**
 * @file    hello_extended_receiver.idl
 * @author  Marcel Smit
 *
 * @brief   idl receiver component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef HELLO_EXTENDED_RECEIVER_IDL_
#define HELLO_EXTENDED_RECEIVER_IDL_

#include <Components.idl>

#include "hello_extended.idl"

module Hello
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};

#endif /* HELLO_EXTENDED_RECEIVER_IDL_ */
