/**
 * @file    top_union_sender.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef TOP_UNION_SENDER_IDL_
#define TOP_UNION_SENDER_IDL_

#include "top_unionSE.idl"
#include <ccm_timed_trigger.idl>

module Uni
{
  component Sender
  {
    port TopUnionConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;

    uses CCM_TT::TT_Scheduler tt_scheduler;
  };
};

#endif /* TOP_UNION_SENDER_IDL_ */
