// -*- C++ -*-
/**
 * @file    ami4ccm_impl_export.h
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef __RIDL_AMI4CCM_IMPL_EXPORT_H_BHDBGCCC_EXPORT_INCLUDED__
#define __RIDL_AMI4CCM_IMPL_EXPORT_H_BHDBGCCC_EXPORT_INCLUDED__

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (AMI4CCM_IMPL_HAS_DLL)
#  define AMI4CCM_IMPL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && AMI4CCM_IMPL_HAS_DLL */

#if !defined (AMI4CCM_IMPL_HAS_DLL)
#  define AMI4CCM_IMPL_HAS_DLL 1
#endif /* ! AMI4CCM_IMPL_HAS_DLL */

#if defined (AMI4CCM_IMPL_HAS_DLL) && (AMI4CCM_IMPL_HAS_DLL == 1)
#  if defined (AMI4CCM_IMPL_BUILD_DLL)
#    define AMI4CCM_IMPL_Export ACE_Proper_Export_Flag
#    define AMI4CCM_IMPL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define AMI4CCM_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* AMI4CCM_IMPL_BUILD_DLL */
#    define AMI4CCM_IMPL_Export ACE_Proper_Import_Flag
#    define AMI4CCM_IMPL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define AMI4CCM_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* AMI4CCM_IMPL_BUILD_DLL */
#else /* AMI4CCM_IMPL_HAS_DLL == 1 */
#  define AMI4CCM_IMPL_Export
#  define AMI4CCM_IMPL_SINGLETON_DECLARATION(T)
#  define AMI4CCM_IMPL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* AMI4CCM_IMPL_HAS_DLL == 1 */

#endif /* __RIDL_AMI4CCM_IMPL_EXPORT_H_BHDBGCCC_EXPORT_INCLUDED__ */
