/**
 * @file    union_sender.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef UNION_SENDER_IDL_
#define UNION_SENDER_IDL_

#include "unionSE.idl"
#include <ccm_timed_trigger.idl>

module Uni
{
  component Sender
  {
    port UnionConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;

    uses CCM_TT::TT_Scheduler tt_scheduler;
  };
};

#endif /* UNION_SENDER_IDL_ */
