/**
 * @file   log_backend_export.h
 * @author Johnny Willemsen
 *
 * @brief  Export file for logging backend
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef DNCX11_LOG_BACKEND_EXPORT_H
#define DNCX11_LOG_BACKEND_EXPORT_H

#include "tao/x11/base/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (DNCX11_LOG_BACKEND_HAS_DLL)
#  define DNCX11_LOG_BACKEND_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && DNCX11_LOG_BACKEND_HAS_DLL */

#if !defined (DNCX11_LOG_BACKEND_HAS_DLL)
#  define DNCX11_LOG_BACKEND_HAS_DLL 1
#endif /* ! DNCX11_LOG_BACKEND_HAS_DLL */

#if defined (DNCX11_LOG_BACKEND_HAS_DLL) && (DNCX11_LOG_BACKEND_HAS_DLL == 1)
#  if defined (DNCX11_LOG_BACKEND_BUILD_DLL)
#    define DNCX11_LOG_BACKEND_Export TAOX11_Proper_Export_Flag
#    define DNCX11_LOG_BACKEND_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define DNCX11_LOG_BACKEND_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DNCX11_LOG_BACKEND_BUILD_DLL */
#    define DNCX11_LOG_BACKEND_Export TAOX11_Proper_Import_Flag
#    define DNCX11_LOG_BACKEND_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define DNCX11_LOG_BACKEND_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DNCX11_LOG_BACKEND_BUILD_DLL */
#else /* DNCX11_LOG_BACKEND_HAS_DLL == 1 */
#  define DNCX11_LOG_BACKEND_Export
#  define DNCX11_LOG_BACKEND_SINGLETON_DECLARATION(T)
#  define DNCX11_LOG_BACKEND_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DNCX11_LOG_BACKEND_HAS_DLL == 1 */

#endif /* DNCX11_LOG_BACKEND_EXPORT_H */

