/**
 * @file    ddsx11_testlog.h
 * @author  Johnny Willemsen
 *
 * @brief   DDSX11 Test Logging module
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DDSX11_TESTLOG_H
#define DDSX11_TESTLOG_H

#include "logger/ddsx11_log.h"

#if defined(X11_NLOGGING)
#define DDSX11_TEST_LOGGER   x11_logger::NULL_LogType
#else
#define DDSX11_TEST_LOGGER DDSX11::ddsx11_logger::DDSX11_Test_Log_Module::log_type
#endif /* !X11_NLOGGING */

#define DDSX11_TEST_TRACE      X11_TRACE_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_DEBUG      X11_DEBUG_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_INFO       X11_INFO_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_WARNING    X11_WARNING_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_ERROR      X11_ERROR_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_CRITICAL   X11_CRITICAL_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_PANIC      X11_PANIC_LOG(DDSX11_TEST_LOGGER)

#define DDSX11_TEST_TRACE_W    X11_TRACE_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_DEBUG_W    X11_DEBUG_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_INFO_W     X11_INFO_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_WARNING_W  X11_WARNING_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_ERROR_W    X11_ERROR_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_CRITICAL_W X11_CRITICAL_W_LOG(DDSX11_TEST_LOGGER)
#define DDSX11_TEST_PANIC_W    X11_PANIC_W_LOG(DDSX11_TEST_LOGGER)

#endif /* DDSX11_TESTLOG_H */
