/**
 * @file    ccm_enterprisecomponent.idl
 * @author  Johnny Willemsen
 *
 * @brief   Compliant with OMG formal/2021-02-04 Section 9.3.2
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#if !defined (CCM_ENTERPRISECOMPONENT_IDL)
#define CCM_ENTERPRISECOMPONENT_IDL

module Components
{
  typeprefix Components "omg.org";

  local interface EnterpriseComponent {};
};
#endif /* CCM_CONTAINER_IDL */
