/**
 * @file    ccm_serviceregistry.idl
 * @author  Johnny Willemsen
 *
 * @brief   Service registry interface
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#include "ccm/ccm_ccmexception.idl"

module CIAOX11
{
  /// Registry with optional services that
  /// can be installed into the container
  local interface Service_Registry
  {
    /// Install the service with @a service_id as name
    /// Throws a Components::CCMException at the moment the @a service_id
    /// is empty, @a obj is empty, or already registered
    void install_service (in string service_id,
                          in Object obj);

    /// Uninstall a service with @a service_id as name
    /// Throws a Components::CCMException exception
    /// when there is no service registered with @a service_id
    Object uninstall_service (in string service_id);

    /// Find a service with @a service_id as name
    /// Throws a Components::CCMException exception when there is no
    /// service registered with @a service_id
    Object resolve_service (in string service_id)
      raises (Components::CCMException);
  };

  /// Standard service ids
  const string SVCID_ORB = "ORB";
};

