/**
 * @file    ccm_config.idl
 * @author  Johnny Willemsen
 *
 * @brief   Compliant with OMG formal/2021-02-04 Section 6.11.1.2
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#if !defined (CCM_CONFIG_IDL)
#define CCM_CONFIG_IDL

#include "ccm/ccm_featurename.idl"

module Components
{
  typeprefix Components "omg.org";

  /// Changed for CIAOX11 from a valuetype to a struct.
  /// We only need to store the string/any pair
  struct ConfigValue
  {
    FeatureName name;
    any value;
  };

  typedef sequence<ConfigValue> ConfigValues;
};

#endif /* CCM_CONFIG_IDL */
