/**
 * @file    ccm_featurename.idl
 * @author  Johnny Willemsen
 *
 * @brief   Compliant with OMG formal/2021-02-04 Section 6.5.3.3
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#if !defined (CCM_FEATURENAME_IDL)
#define CCM_FEATURENAME_IDL

module Components
{
  typeprefix Components "omg.org";

  typedef string FeatureName;
  typedef sequence<FeatureName> NameList;
};
#endif /* CCM_FEATURENAME_IDL */
