/**
 * @file    keywords.idl
 * @author  Johnny Willemsen
 *
 * Tests handling of C++ keywords and escaped identifiers (IDL
 * keywords) in generating CIAO servant code and executor IDL.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef KEYWORD_CLASH_IDL
#define KEYWORD_CLASH_IDL

#include "Components.idl"

module _interface
{
  interface _attribute
  {
    exception _inout {};
  };
};

module static
{
  module _readonly
  {
    module protected
    {
      interface virtual
      {
      };

      interface _port
      {
      };

      interface _alias
      {
      };

      interface _mirrorport
      {
      };

      interface _porttype
      {
      };

      interface _connector
      {
      };
    };
  };
};

interface _oneway {};

module _component
{
  component _out
  {
    provides _interface::_attribute _local;
    provides _oneway else;
    provides static::_readonly::protected::virtual while;

    attribute long _abstract;

    uses multiple _interface::_attribute if;
    uses multiple _oneway mutable;
    uses multiple static::_readonly::protected::virtual register;

    uses _interface::_attribute _union;
    uses _oneway _struct;
    uses static::_readonly::protected::virtual volatile;
  };
};

#endif /* KEYWORD_CLASH_IDL */

