/**
 * @file    hello_sender.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   Sender component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "base/hello.idl"

module Hello
{
  component Sender
  {
    port Write sender_write_port;
    attribute short ojee;
  };
};

#endif
