/**
 * @file   ciaox11_corba_util_export.h
 * @author Martin Corino
 *
 * @brief CIAOX11 CORBA deployment utility export header
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef __CIAOX11_CORBA_UTIL_EXPORT_H_INCLUDED__
#define __CIAOX11_CORBA_UTIL_EXPORT_H_INCLUDED__

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (CIAOX11_CORBA_UTIL_HAS_DLL)
#  define CIAOX11_CORBA_UTIL_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && CIAOX11_CORBA_UTIL_HAS_DLL */

#if !defined (CIAOX11_CORBA_UTIL_HAS_DLL)
#  define CIAOX11_CORBA_UTIL_HAS_DLL 1
#endif /* ! CIAOX11_CORBA_UTIL_HAS_DLL */

#if defined (CIAOX11_CORBA_UTIL_HAS_DLL) && (CIAOX11_CORBA_UTIL_HAS_DLL == 1)
#  if defined (CIAOX11_CORBA_UTIL_BUILD_DLL)
#    define CIAOX11_CORBA_UTIL_Export ACE_Proper_Export_Flag
#    define CIAOX11_CORBA_UTIL_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define CIAOX11_CORBA_UTIL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CIAOX11_CORBA_UTIL_BUILD_DLL */
#    define CIAOX11_CORBA_UTIL_Export ACE_Proper_Import_Flag
#    define CIAOX11_CORBA_UTIL_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define CIAOX11_CORBA_UTIL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CIAOX11_CORBA_UTIL_BUILD_DLL */
#else /* CIAOX11_CORBA_UTIL_HAS_DLL == 1 */
#  define CIAOX11_CORBA_UTIL_Export
#  define CIAOX11_CORBA_UTIL_SINGLETON_DECLARATION(T)
#  define CIAOX11_CORBA_UTIL_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CIAOX11_CORBA_UTIL_HAS_DLL == 1 */

#endif /* __CIAOX11_CORBA_UTIL_EXPORT_H_INCLUDED__ */
