/**
 * @file    hello4.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   Data interfaces for minimal sync manual example
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO4_IDL_
#define HELLO4_IDL_

module Hello
{
  struct S2 {
    long s_long;
  };
};

#endif /* HELLO4_IDL_ */
