/**
 * @file    hello_receiver.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   receiver for test with missing connection
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef HELLO_T_RECEIVER_IDL
#define HELLO_T_RECEIVER_IDL

#include <Components.idl>

#include "hello.idl"

module HelloT
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
