/**
 * @file    dds4ccm_testlog.h
 * @author  Marcel Smit
 *
 * @brief   DDS4CCM Test Logging module
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DDS4CCM_TESTLOG_H
#define DDS4CCM_TESTLOG_H

#include "dds4ccm/logger/dds4ccm_log.h"

#if defined(X11_NLOGGING)
#define DDS4CCM_TEST_LOGGER   x11_logger::NULL_LogType
#else
#define DDS4CCM_TEST_LOGGER CIAOX11::DDS4CCM::dds4ccm_logger::DDS4CCM_Test_Log_Module::log_type
#endif /* !X11_NLOGGING */

#define DDS4CCM_TEST_TRACE      X11_TRACE_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_DEBUG      X11_DEBUG_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_INFO       X11_INFO_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_WARNING    X11_WARNING_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_ERROR      X11_ERROR_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_CRITICAL   X11_CRITICAL_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_PANIC      X11_PANIC_LOG(DDS4CCM_TEST_LOGGER)

#define DDS4CCM_TEST_TRACE_W    X11_TRACE_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_DEBUG_W    X11_DEBUG_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_INFO_W     X11_INFO_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_WARNING_W  X11_WARNING_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_ERROR_W    X11_ERROR_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_CRITICAL_W X11_CRITICAL_W_LOG(DDS4CCM_TEST_LOGGER)
#define DDS4CCM_TEST_PANIC_W    X11_PANIC_W_LOG(DDS4CCM_TEST_LOGGER)

#endif /* DDS4CCM_TESTLOG_H */
