/**
 * @file    dds4ccm_logger_export.h
 * @author  Unknown
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DDS4CCM_LOGGER_EXPORT_H
#define DDS4CCM_LOGGER_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (DDS4CCM_LOGGER_HAS_DLL)
#  define DDS4CCM_LOGGER_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && DDS4CCM_LOGGER_HAS_DLL */

#if !defined (DDS4CCM_LOGGER_HAS_DLL)
#  define DDS4CCM_LOGGER_HAS_DLL 1
#endif /* ! DDS4CCM_LOGGER_HAS_DLL */

#if defined (DDS4CCM_LOGGER_HAS_DLL) && (DDS4CCM_LOGGER_HAS_DLL == 1)
#  if defined (DDS4CCM_LOGGER_BUILD_DLL)
#    define DDS4CCM_Logger_Export TAOX11_Proper_Export_Flag
#    define DDS4CCM_LOGGER_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define DDS4CCM_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DDS4CCM_LOGGER_BUILD_DLL */
#    define DDS4CCM_Logger_Export TAOX11_Proper_Import_Flag
#    define DDS4CCM_LOGGER_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define DDS4CCM_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DDS4CCM_LOGGER_BUILD_DLL */
#else /* DDS4CCM_LOGGER_HAS_DLL == 1 */
#  define DDS4CCM_Logger_Export
#  define DDS4CCM_LOGGER_SINGLETON_DECLARATION(T)
#  define DDS4CCM_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DDS4CCM_LOGGER_HAS_DLL == 1 */

#endif /* DDS4CCM_LOGGER_EXPORT_H */

