/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
* Chamber of commerce Rotterdam nr.276339, The Netherlands
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  typedef sequence<unsigned long, 10> ULongSeq;

  struct Topic
  {
    string category;
    string description;
    ULongSeq values;

  }; //@TopLevel()
};

#endif
