/**
 * @file    starter_code_connr.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   CIAOX11 connector for connector test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef BASE_CONNECTOR_CONN_IDL
#define BASE_CONNECTOR_CONN_IDL

#include <Components.idl>

#include "hello.idl"

module Hello
{
  connector MyBaseEvent
  {
    mirrorport Listen consumer;
    attribute short conn_attrib;
  };
};

#endif


