/**
 * @file    in_args_t_receiver.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   base of sender ami4ccm test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef INTERINARGS_T_RECEIVER_IDL
#define INTERINARGS_T_RECEIVER_IDL

#include <Components.idl>

#include "in_args_t.idl"

module InterInArgsT
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
