/**
 * @file    ddsx11_logger_export.h
 * @author  Unknown
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DDSX11_LOGGER_EXPORT_H
#define DDSX11_LOGGER_EXPORT_H

#include "tao/x11/base/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (DDSX11_LOGGER_HAS_DLL)
#  define DDSX11_LOGGER_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && DDSX11_LOGGER_HAS_DLL */

#if !defined (DDSX11_LOGGER_HAS_DLL)
#  define DDSX11_LOGGER_HAS_DLL 1
#endif /* ! DDSX11_LOGGER_HAS_DLL */

#if defined (DDSX11_LOGGER_HAS_DLL) && (DDSX11_LOGGER_HAS_DLL == 1)
#  if defined (DDSX11_LOGGER_BUILD_DLL)
#    define DDSX11_Logger_Export TAOX11_Proper_Export_Flag
#    define DDSX11_LOGGER_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define DDSX11_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DDSX11_LOGGER_BUILD_DLL */
#    define DDSX11_Logger_Export TAOX11_Proper_Import_Flag
#    define DDSX11_LOGGER_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define DDSX11_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DDSX11_LOGGER_BUILD_DLL */
#else /* DDSX11_LOGGER_HAS_DLL == 1 */
#  define DDSX11_Logger_Export
#  define DDSX11_LOGGER_SINGLETON_DECLARATION(T)
#  define DDSX11_LOGGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DDSX11_LOGGER_HAS_DLL == 1 */

#endif /* DDSX11_LOGGER_EXPORT_H */

