/**
 * @file    invalid_qos_component.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef INVALID_QOS_COMPONENT_IDL_
#define INVALID_QOS_COMPONENT_IDL_

#include "commonSE.idl"

component InvalidQosComponent
{
  port CommonTestConnector::DDS_Write  info_write;
};

#endif /* INVALID_QOS_COMPONENT_IDL_ */
