/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  typedef unsigned long ULongArray[2][25];

  @nested(FALSE)
  struct Topic
  {
    string category;
    string description;
    ULongArray values;

  };
};

#endif
