/**
* @file    topic.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
* Chamber of commerce Rotterdam nr.276339, The Netherlands
*/

#ifndef TOPIC_IDL
#define TOPIC_IDL

module Test
{
  typedef unsigned long ULongArray[2][25];

  struct Topic
  {
    string category;
    string description;
    ULongArray values;

  }; //@TopLevel()
};

#endif
