/**
 * @file    hello_receiver.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   Receiver component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "hello.idl"

module Hello
{
  component Receiver
  {
    /// Provides
    attribute short aap;
    port Listen rec_listen_port;
  };
};
#endif
