/**
 * @file    foo.idl
 * @author  Martin Corino
 *
 * @brief   Foo interface declaration
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef FOO_IDL_
#define FOO_IDL_

module Example
{
  // Foo interface
  interface Foo
  {
    void do_something (in string an_argument);
  };
};

#endif /* FOO_IDL_ */
