/**
 * @file    custom_example_connector.idl
 * @author  Marcel Smit
 *
 * @brief   Stress test for DDS4CCM
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef CX_PORTS__EXAMPLE_CA1_CONN_IDL
#define CX_PORTS__EXAMPLE_CA1_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "custom_example_ca1_msg.idl"

/// @namespace Example
module Example {
    /// @typedef CA1_msgSeq
    typedef sequence <CA1_msg> CA1_msgSeq;
    module CCM_DDS::Typed <CA1_msg, CA1_msgSeq> CA1_conn;
};

#endif // CX_PORTS__EXAMPLE_CA1_CONN_IDL
