/**
* @file    message.idl
* @author  Martin Corino
*
* @brief   Message topic IDL
*
* @copyright Copyright (c) Remedy IT Expertise BV
*/

#ifndef MESSAGE_IDL
#define MESSAGE_IDL

module Test
{
  struct Message
  {
    string category; //@key
    string description;
    unsigned long value;
  }; //@nested(FALSE)
};

#endif
