/**
 * @file    shapetype.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef SHAPES_SHAPETYPE_MSG_IDL_
#define SHAPES_SHAPETYPE_MSG_IDL_

typedef string<128> color_type;

struct ShapeType {
  color_type color; //@key
  long x;
  long y;
  long shapesize;
}; //@nested(FALSE)

#endif /* SHAPES_SHAPETYPE_MSG_IDL_ */
