/**
 * @file    user.idl
 * @author  Martin Corino
 *
 * @brief   User component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef USER_IDL_
#define USER_IDL_

#include <Components.idl>
#include <ccm_timed_trigger.idl>

#include "foo.idl"
#include "bar.idl"

module Example
{
  component User
  {
    uses Foo run_my_foo;
    uses Bar run_my_bar;

    attribute string connection;

    uses CCM_TT::TT_Scheduler tt_scheduler;
  };
};

#endif /* USER_IDL_ */
