/**
 * @file    top_union_receiver.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef TOP_UNION_RECEIVER_IDL_
#define TOP_UNION_RECEIVER_IDL_

#include "top_unionSE.idl"

module Uni
{
  component Receiver
  {
    port TopUnionConnector::DDS_Listen info_out;
  };
};

#endif /* TOP_UNION_RECEIVER_IDL_ */
