/**
 * @file    multi_inherit.idl
 * @author  Martin Corino
 *
 * @brief   base of ami4ccm test with multiple inheritance
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef INTERMULTI_IDL
#define INTERMULTI_IDL

#include "base.idl"

#pragma ami4ccm interface "InterMulti::Three"
#pragma ami4ccm idl "multi_inheritA.idl"

module InterMulti
{
  //multiple inheritance
  interface Three: One, Two
    {
       void plus (in long cmd, out string answer)
         raises (InternalError);
    };
};

#endif
