/**
 * @file    shapes_defn.idl
 * @author  Johnny Willemsen
 *
 * @brief   Shapes type definition file
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef SHAPES_DEFN_IDL_
#define SHAPES_DEFN_IDL_

module Shapes
{
  enum ReturnStatus
  {
    RETURN_OK,
    RETURN_ERROR
  };
};

#endif /* SHAPES_DEFN_IDL_ */
