/**
 * @file    cft_el_sender.idl
 * @author  Marcel Smit
 *
 * @brief   Connector IDL for the usage of content filtered topics, making use
 *          of a event listener
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef CFT_EL_SENDER_IDL_
#define CFT_EL_SENDER_IDL_

#include "commonSE.idl"
#include <ccm_timed_trigger.idl>

module CFT_EL_Test
{
  component Sender
  {
    port CommonTestConnector::DDS_Write info_write;
    provides CCM_DDS::ConnectorStatusListener connector_status;

    uses CCM_TT::TT_Scheduler tt_scheduler;

    attribute unsigned short keys;
    attribute unsigned short iterations;
  };
};

#endif /* CFT_EL_SENDER_IDL_ */
