/**
 * @file   tt4ccm_exf_conn_export.h
 * @author Marijke Hengstmengel
 *
 * @brief Export file for timer connector with EXF.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef __RIDL_TT4CCM_EXF_CONN_EXPORT_H_IBEFHFHA_EXPORT_INCLUDED__
#define __RIDL_TT4CCM_EXF_CONN_EXPORT_H_IBEFHFHA_EXPORT_INCLUDED__

#include "ace/config-all.h"

#include "tao/x11/base/versionx11.h"


#if defined (ACE_AS_STATIC_LIBS) && !defined (TT4CCM_EXF_CONN_HAS_DLL)
#  define TT4CCM_EXF_CONN_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TT4CCM_EXF_CONN_HAS_DLL */

#if !defined (TT4CCM_EXF_CONN_HAS_DLL)
#  define TT4CCM_EXF_CONN_HAS_DLL 1
#endif /* ! TT4CCM_EXF_CONN_HAS_DLL */

#if defined (TT4CCM_EXF_CONN_HAS_DLL) && (TT4CCM_EXF_CONN_HAS_DLL == 1)
#  if defined (TT4CCM_EXF_CONN_BUILD_DLL)
#    define TT4CCM_EXF_CONN_Export ACE_Proper_Export_Flag
#    define TT4CCM_EXF_CONN_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TT4CCM_EXF_CONN_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TT4CCM_EXF_CONN_BUILD_DLL */
#    define TT4CCM_EXF_CONN_Export ACE_Proper_Import_Flag
#    define TT4CCM_EXF_CONN_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TT4CCM_EXF_CONN_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TT4CCM_EXF_CONN_BUILD_DLL */
#else /* TT4CCM_EXF_CONN_HAS_DLL == 1 */
#  define TT4CCM_EXF_CONN_Export
#  define TT4CCM_EXF_CONN_SINGLETON_DECLARATION(T)
#  define TT4CCM_EXF_CONN_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TT4CCM_EXF_CONN_HAS_DLL == 1 */

#endif /* __RIDL_TT4CCM_EXF_CONN_EXPORT_H_IBEFHFHA_EXPORT_INCLUDED__ */
