/**
 * @file    hello_receiver.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   idl receiver component
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "base/hello.idl"

module Hello
{
  component Receiver
  {
    /// Provides
    provides MyFoo do_my_foo;
  };
};
#endif
