/**
 * @file    hello_receiver.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef HELLO_RECEIVER_IDL
#define HELLO_RECEIVER_IDL

#include <Components.idl>

#include "hello.idl"

module Hello
{
  component Receiver
  {
    provides MyFoo do_my_foo;
  };
};
#endif
