/**
 * @file    sync_event_receiver.idl
 * @author  Martin Corino
 *
 * @brief   Receiver component declaration for manual minimal-event test.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef EVENT_RECEIVER_IDL_
#define EVENT_RECEIVER_IDL_

#include "event_recordSE.idl"
#include "hello.idl"

module Hello
{
  component Receiver
  {
    provides MyFoo do_my_foo;

    port ShapeTypeInterface::DDS_Listen info_out;
    attribute unsigned short iterations;
    attribute unsigned short keys;
  };
};

#endif /* EVENT_RECEIVER_IDL_ */
