/**
 * @file    corba4ccm_exceptions.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#ifndef CORBA4CCM_EXCEPTIONS_IDL_
#define CORBA4CCM_EXCEPTIONS_IDL_


interface Hello
{
  void say_hello ();
};

#endif
