/**
 * @file    derived.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef DERIVED_IDL_
#define DERIVED_IDL_


interface Hello
{
  void say_hello ();
};

interface Bye : Hello
{
  void say_bye ();
};

#endif
