/**
 * @file    hello_sender.idl
 * @author  Marijke Hengstmengel
 *
 * @brief   base of sender ami4ccm test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

#ifndef HELLO_SENDER_IDL
#define HELLO_SENDER_IDL

#include <Components.idl>

#include "hello.idl"

#pragma ami4ccm receptacle "Hello::Sender::run_my_foo"

module Hello
{
  component Sender
  {
    /// Provide control interface
    provides Control do_control;

    /// For synchronous invocation
    uses MyFoo run_my_foo;

    /// Also provide interface that has AMI annotation
    provides MyFoo do_my_foo;
  };
};

#endif
