/**
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT Expertise BV
 *        The Netherlands
 *        https://www.remedy.nl
 */

#ifndef __RIDL_STRINGPS_SVNT_H_CJAFFHEG_INCLUDED__
#define __RIDL_STRINGPS_SVNT_H_CJAFFHEG_INCLUDED__

#pragma once

#include /**/ "hello_svnt_export.h"

#include "stringPSEC.h"

#include "ccm/ccm_serviceregistryC.h"
#include "ccm/ccm_executorlocatorC.h"

#include /**/ "ciaox11/versionx11.h"

#if CIAOX11_MAJOR_VERSION != 2 || CIAOX11_MINOR_VERSION != 3 || CIAOX11_MICRO_VERSION != 0
#error This file was generated with another RIDL CCMX11 backend version (2.3.0). Please re-generate.
#endif

// generated from ccmx11/templates/svnt/hdr/exf/psdd/component
namespace Test_Hello_PSDD_Event_Impl
{

  /**
   * Context implementation class for the ::Test::Hello::CCM_PSDD_Event
   * component.
   */
  class PSDD_Event_Context final
    : public IDL::traits< ::Test::Hello::CCM_PSDD_Event_Context>::base_type
  {
  public:
    /**
     * Constructor for the context.
     * @param svcreg The ServiceRegistry for this component
     * @param ins_name The name of the component instance as mentioned in the deployment plan.
     */
    PSDD_Event_Context (IDL::traits<CIAOX11::Service_Registry>::ref_type svcreg, std::string ins_name);

    /// Destructor
    ~PSDD_Event_Context () override = default;

    /// Retrieve the service registry
    IDL::traits<CIAOX11::Service_Registry>::ref_type the_service_registry () override;

    /// @name Accessors for all receptacles
    //@{
    /// Get the consumer_data_listener receptacle
    IDL::traits< ::Test::Hello::Listener>::ref_type get_connection_consumer_data_listener () override;
    //@}
    // generated from ccmx11/templates/svnt/hdr/exf/psdd/connector_context_extra_receptacles

    /// @name Configuration accessors for all receptacles
    //@{
    /// Get the consumer_data_listener receptacle configuration
    ::Components::ConfigValues consumer_data_listener_configuration () override;
    //@}

    friend class PSDD_Event_ExecutorLocator;

    /// readonly attribute which holds the instance name of the
    /// component. This instance name is supplied to the servant factory
    /// method by the deployment tools and represents the name of the
    /// component in the deployment plan.
    std::string instance_id () override;

  private:

    // generated from exf4psdd/templates/svnt/hdr/exf/psdd/context_set_connection
    /// Connect method to set the connection for receptacle with name @a name.
    bool set_connection (const std::string& name,
                         IDL::traits<CORBA::Object>::ref_type port,
                         const ::Components::ConfigValues& config);

    // generated from ccmx11/templates/svnt/hdr/exf/psdd/context_reset_connection
    /// Disconnect method to reset the connection for receptacle with name @a name
    bool reset_connection (const std::string& name);

    /// The ServiceRegistry for this component
    IDL::traits<CIAOX11::Service_Registry>::ref_type service_registry_ {};
    /// The instance name of the component
    std::string const instance_id_ {};

    /// @name Member variables for storing all receptacles
    //@{
    /// Member variable for storing a reference for the consumer_data_listener receptacle
    IDL::traits< ::Test::Hello::Listener>::ref_type consumer_data_listener_{};
    //@}

    // generated from exf4psdd/templates/svnt/hdr/exf/psdd/context_extra_members

    /// @name Member variables for storing all receptacle configurations
    //@{
    /// Member variable for the consumer_data_listener receptacle configuration
    ::Components::ConfigValues consumer_data_listener_config_;
    //@}

    //@{
    /** Illegal to be called. Deleted explicitly to let the compiler detect any violation */
    PSDD_Event_Context () = delete;
    PSDD_Event_Context (const PSDD_Event_Context&) = delete;
    PSDD_Event_Context (PSDD_Event_Context&&) = delete;
    PSDD_Event_Context& operator= (const PSDD_Event_Context&) = delete;
    PSDD_Event_Context& operator= (PSDD_Event_Context&&) = delete;
    //@}
  };

  /**
   * ExecutorLocator for the PSDD_Event component. This
   * gives access to all middleware generated pieces that are used
   * by the CCM infrastructure
   */
  class PSDD_Event_ExecutorLocator final
    : public IDL::traits<CIAOX11::ExecutorLocator>::base_type
  {
  public:
    /**
    * Constructor
    * @param component_executor The user implemented executor
    * @param component_context The context that is passed to the executor
    */
    PSDD_Event_ExecutorLocator (
      IDL::traits<::Test::Hello::CCM_PSDD_Event>::ref_type component_executor,
      IDL::traits<PSDD_Event_Context>::ref_type component_context);

    /// Destructor
    ~PSDD_Event_ExecutorLocator () override = default;

    /**
     * Configure the component
     */
    void configure (::Components::ConfigValues& config) override;

    /**
     * Connect a component port.
     * @retval true Connecting the port has succeeded
     * @retval false Connecting the port has failed
     */
    bool connect (const ::Components::FeatureName& name,
                  IDL::traits<CORBA::Object>::ref_type connection,
                  const std::string& conn_name,
                  const ::Components::ConfigValues& config) override;

    /**
     * Disconnect a component port.
     * @retval true Disconnecting the port has succeeded
     * @retval false Disconnecting the port has failed
     */
    bool disconnect (const ::Components::FeatureName& name,
                     const std::string& conn_name) override;

    /**
     * Obtain the component executor.
     */
    IDL::traits<CORBA::Object>::ref_type obtain_executor () override;

    /**
     * Obtain a facet executor for the given @a name using the the given @a config.
     * If there is no facet executor returned by the component executor we just
     * return nullptr. If we have to get an executor for an invalid facet
     * name we throw an InvalidName() exception
     */
    IDL::traits<CORBA::Object>::ref_type obtain_facet_executor (
                          const ::Components::FeatureName& name,
                          ::Components::ConfigValues& config) override;

  private:
    /**
    * At the moment a component has attributes, we loop
    * through the passed set and based on the name of the
    * attribute call a setter of the executor we have as member.
    * Throws a CIAOX11::ConfigurationError at the moment one or more
    * of the matching config values can't be set on the executor
    * (extraction errors or readonly attributes).
    */
    void set_configuration (const Components::ConfigValues& descr);

    /// Reference to the user implemented executor
    IDL::traits<::Test::Hello::CCM_PSDD_Event>::ref_type component_executor_;

    /// The context for this component
    IDL::traits<PSDD_Event_Context>::ref_type component_context_;

    /** @name Illegal to be called. Deleted explicitly to let the compiler detect any violation */
    //@{
    PSDD_Event_ExecutorLocator () = delete;
    PSDD_Event_ExecutorLocator (const PSDD_Event_ExecutorLocator&) = delete;
    PSDD_Event_ExecutorLocator (PSDD_Event_ExecutorLocator&&) = delete;
    PSDD_Event_ExecutorLocator& operator= (const PSDD_Event_ExecutorLocator&) = delete;
    PSDD_Event_ExecutorLocator& operator= (PSDD_Event_ExecutorLocator&&) = delete;
    //@}
  };
} // namespace Test_Hello_PSDD_Event_Impl

/**
 * Factory method to create an executor locator for a
 * Test_Hello_PSDD_Event_Impl component
 * @param component_executor The user component executor for which we need
 * to create the executor locator
 * @param svcreg The ServiceRegistry for this component
 * @param ins_name The unique name of this component
 * @param executor_locator The created executor locator
 */
extern "C" HELLO_SVNT_Export  void
create_Test_Hello_PSDD_Event_Servant (
  IDL::traits<Components::EnterpriseComponent>::ref_type component_executor,
  IDL::traits<CIAOX11::Service_Registry>::ref_type svcreg,
  const std::string& ins_name,
  IDL::traits<CIAOX11::ExecutorLocator>::ref_type& executor_locator);

#endif /* __RIDL_STRINGPS_SVNT_H_CJAFFHEG_INCLUDED__ */

// -*- END -*-
