/**
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT Expertise BV
 *        The Netherlands
 *        https://www.remedy.nl
 */

#ifndef __RIDL_STRINGPS_CONN_H_JFAFBEBJ_INCLUDED__
#define __RIDL_STRINGPS_CONN_H_JFAFBEBJ_INCLUDED__

#pragma once

#include "ccm/ccm_enterprisecomponentC.h"

#include /**/ "hello_conn_export.h"

#include /**/ "ciaox11/versionx11.h"

#if CIAOX11_MAJOR_VERSION != 2 || CIAOX11_MINOR_VERSION != 3 || CIAOX11_MICRO_VERSION != 0
#error This file was generated with another RIDL CCMX11 backend version (2.3.0). Please re-generate.
#endif

// generated from ccmx11/templates/conn_templ/hdr/connector
extern "C" HELLO_CONN_Export  void
create_Test_Hello_PSDD_Event_Impl (
  IDL::traits<Components::EnterpriseComponent>::ref_type& component);

#endif /* __RIDL_STRINGPS_CONN_H_JFAFBEBJ_INCLUDED__ */
